import Foundation

// `@Observable` changes stored properties into macro-generated backing storage.
// Explicit Codable implementations keep the persisted UserDefaults snapshot
// stable across Swift compiler versions.
extension Child {
    convenience init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.init(id: try c.decode(String.self, forKey: .id), name: try c.decode(String.self, forKey: .name), familyId: try c.decode(String.self, forKey: .familyId), avatar: try c.decode(ChildAvatar.self, forKey: .avatar), dateOfBirth: try c.decodeIfPresent(Date.self, forKey: .dateOfBirth), activePoints: try c.decode(Int.self, forKey: .activePoints), totalPointsEarned: try c.decode(Int.self, forKey: .totalPointsEarned), createdAt: try c.decode(Date.self, forKey: .createdAt), updatedAt: try c.decode(Date.self, forKey: .updatedAt))
    }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(name, forKey: .name); try c.encode(familyId, forKey: .familyId); try c.encode(avatar, forKey: .avatar); try c.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth); try c.encode(activePoints, forKey: .activePoints); try c.encode(totalPointsEarned, forKey: .totalPointsEarned); try c.encode(createdAt, forKey: .createdAt); try c.encode(updatedAt, forKey: .updatedAt) }
}

extension Family {
    convenience init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); self.init(id: try c.decode(String.self, forKey: .id), name: try c.decode(String.self, forKey: .name), memberIds: try c.decode([String].self, forKey: .memberIds), settings: try c.decode(FamilySettings.self, forKey: .settings), createdAt: try c.decode(Date.self, forKey: .createdAt), updatedAt: try c.decode(Date.self, forKey: .updatedAt)) }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(name, forKey: .name); try c.encode(memberIds, forKey: .memberIds); try c.encode(settings, forKey: .settings); try c.encode(createdAt, forKey: .createdAt); try c.encode(updatedAt, forKey: .updatedAt) }
}

extension KiddoTask {
    convenience init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); self.init(id: try c.decode(String.self, forKey: .id), familyId: try c.decode(String.self, forKey: .familyId), name: try c.decode(String.self, forKey: .name), description: try c.decode(String.self, forKey: .description), icon: try c.decode(String.self, forKey: .icon), category: try c.decode(TaskCategory.self, forKey: .category), pointValue: try c.decode(Int.self, forKey: .pointValue), requiresApproval: try c.decode(Bool.self, forKey: .requiresApproval), assignedChildIds: try c.decode([String].self, forKey: .assignedChildIds), recurrence: try c.decode(TaskRecurrence.self, forKey: .recurrence), isActive: try c.decode(Bool.self, forKey: .isActive), createdBy: try c.decode(String.self, forKey: .createdBy), createdAt: try c.decode(Date.self, forKey: .createdAt), updatedAt: try c.decode(Date.self, forKey: .updatedAt), version: try c.decode(Int.self, forKey: .version)) }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(familyId, forKey: .familyId); try c.encode(name, forKey: .name); try c.encode(description, forKey: .description); try c.encode(icon, forKey: .icon); try c.encode(category, forKey: .category); try c.encode(pointValue, forKey: .pointValue); try c.encode(requiresApproval, forKey: .requiresApproval); try c.encode(assignedChildIds, forKey: .assignedChildIds); try c.encode(recurrence, forKey: .recurrence); try c.encode(isActive, forKey: .isActive); try c.encode(createdBy, forKey: .createdBy); try c.encode(createdAt, forKey: .createdAt); try c.encode(updatedAt, forKey: .updatedAt); try c.encode(version, forKey: .version) }
}

extension Parent {
    convenience init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); self.init(id: try c.decode(String.self, forKey: .id), email: try c.decode(String.self, forKey: .email), displayName: try c.decode(String.self, forKey: .displayName), familyId: try c.decode(String.self, forKey: .familyId), role: try c.decode(ParentRole.self, forKey: .role), createdAt: try c.decode(Date.self, forKey: .createdAt), lastSignInAt: try c.decodeIfPresent(Date.self, forKey: .lastSignInAt)) }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(email, forKey: .email); try c.encode(displayName, forKey: .displayName); try c.encode(familyId, forKey: .familyId); try c.encode(role, forKey: .role); try c.encode(createdAt, forKey: .createdAt); try c.encodeIfPresent(lastSignInAt, forKey: .lastSignInAt) }
}

extension Reward {
    convenience init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); self.init(id: try c.decode(String.self, forKey: .id), familyId: try c.decode(String.self, forKey: .familyId), name: try c.decode(String.self, forKey: .name), description: try c.decode(String.self, forKey: .description), icon: try c.decode(String.self, forKey: .icon), pointCost: try c.decode(Int.self, forKey: .pointCost), eligibleChildIds: try c.decode([String].self, forKey: .eligibleChildIds), requiresApproval: try c.decode(Bool.self, forKey: .requiresApproval), isActive: try c.decode(Bool.self, forKey: .isActive), createdBy: try c.decode(String.self, forKey: .createdBy), createdAt: try c.decode(Date.self, forKey: .createdAt), updatedAt: try c.decode(Date.self, forKey: .updatedAt), version: try c.decode(Int.self, forKey: .version)) }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(familyId, forKey: .familyId); try c.encode(name, forKey: .name); try c.encode(description, forKey: .description); try c.encode(icon, forKey: .icon); try c.encode(pointCost, forKey: .pointCost); try c.encode(eligibleChildIds, forKey: .eligibleChildIds); try c.encode(requiresApproval, forKey: .requiresApproval); try c.encode(isActive, forKey: .isActive); try c.encode(createdBy, forKey: .createdBy); try c.encode(createdAt, forKey: .createdAt); try c.encode(updatedAt, forKey: .updatedAt); try c.encode(version, forKey: .version) }
}

extension TaskCompletion {
    convenience init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); self.init(id: try c.decode(String.self, forKey: .id), familyId: try c.decode(String.self, forKey: .familyId), taskId: try c.decode(String.self, forKey: .taskId), childId: try c.decode(String.self, forKey: .childId), status: try c.decode(CompletionStatus.self, forKey: .status), completedAt: try c.decode(Date.self, forKey: .completedAt), approvedAt: try c.decodeIfPresent(Date.self, forKey: .approvedAt), approvedBy: try c.decodeIfPresent(String.self, forKey: .approvedBy), pointsAwarded: try c.decodeIfPresent(Int.self, forKey: .pointsAwarded), pointTransactionId: try c.decodeIfPresent(String.self, forKey: .pointTransactionId), notes: try c.decodeIfPresent(String.self, forKey: .notes)) }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(familyId, forKey: .familyId); try c.encode(taskId, forKey: .taskId); try c.encode(childId, forKey: .childId); try c.encode(status, forKey: .status); try c.encode(completedAt, forKey: .completedAt); try c.encodeIfPresent(approvedAt, forKey: .approvedAt); try c.encodeIfPresent(approvedBy, forKey: .approvedBy); try c.encodeIfPresent(pointsAwarded, forKey: .pointsAwarded); try c.encodeIfPresent(pointTransactionId, forKey: .pointTransactionId); try c.encodeIfPresent(notes, forKey: .notes) }
}

extension RewardClaim {
    convenience init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); self.init(id: try c.decode(String.self, forKey: .id), familyId: try c.decode(String.self, forKey: .familyId), rewardId: try c.decode(String.self, forKey: .rewardId), childId: try c.decode(String.self, forKey: .childId), status: try c.decode(RewardClaimStatus.self, forKey: .status), claimedAt: try c.decode(Date.self, forKey: .claimedAt), approvedAt: try c.decodeIfPresent(Date.self, forKey: .approvedAt), approvedBy: try c.decodeIfPresent(String.self, forKey: .approvedBy), pointDeductionTransactionId: try c.decodeIfPresent(String.self, forKey: .pointDeductionTransactionId), notes: try c.decodeIfPresent(String.self, forKey: .notes)) }
    func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(id, forKey: .id); try c.encode(familyId, forKey: .familyId); try c.encode(rewardId, forKey: .rewardId); try c.encode(childId, forKey: .childId); try c.encode(status, forKey: .status); try c.encode(claimedAt, forKey: .claimedAt); try c.encodeIfPresent(approvedAt, forKey: .approvedAt); try c.encodeIfPresent(approvedBy, forKey: .approvedBy); try c.encodeIfPresent(pointDeductionTransactionId, forKey: .pointDeductionTransactionId); try c.encodeIfPresent(notes, forKey: .notes) }
}
